## Name : Viraj Vinod Salunke 
## Roll No 59
## ML_Exp1

In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
import numpy as np
# -------------------------
# 1. Array Creation
# -------------------------
# From list
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)


Array from list: [1 2 3 4 5]


In [16]:

# From nested list (matrix)
arr2 = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr2)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [17]:

# Using arange, linspace, zeros, ones, eye
arr_arange = np.arange(0, 10, 2)
print("arange array:", arr_arange)


arange array: [0 2 4 6 8]


In [18]:

arr_linspace = np.linspace(0, 1, 5)
print("linspace array:", arr_linspace)


linspace array: [0.   0.25 0.5  0.75 1.  ]


In [19]:

arr_zeros = np.zeros((2,3))
print("zeros array:\n", arr_zeros)


zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [20]:

arr_ones = np.ones((3,2))
print("ones array:\n", arr_ones)


ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [21]:
arr_eye = np.eye(3)
print("Identity matrix:\n", arr_eye)


Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
# -------------------------
# 2. Array Attributes
# -------------------------
print("Shape of arr2:", arr2.shape)


Shape of arr2: (2, 3)


In [23]:
print("Size of arr2:", arr2.size)


Size of arr2: 6


In [24]:
print("Number of dimensions:", arr2.ndim)


Number of dimensions: 2


In [25]:
print("Data type:", arr2.dtype)


Data type: int64


In [26]:
print("Item size (bytes):", arr2.itemsize)


Item size (bytes): 8


In [27]:

# -------------------------
# 3. Indexing and Slicing
# -------------------------
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("Index 2:", arr[2])
print("Last element:", arr[-1])
print("Slice 1:4:", arr[1:4])


Original array: [10 20 30 40 50]
Index 2: 30
Last element: 50
Slice 1:4: [20 30 40]


In [28]:

# 2D array slicing
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array:\n", arr2d)


2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print("First row:", arr2d[0,:])


First row: [1 2 3]


In [30]:
print("Second column:", arr2d[:,1])


Second column: [2 5 8]


In [31]:
print("Submatrix:\n", arr2d[0:2,1:3])


Submatrix:
 [[2 3]
 [5 6]]


In [32]:

# -------------------------
# 4. Basic Operations
# -------------------------
a = np.array([1,2,3])
b = np.array([4,5,6])
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("a ** 2:", a**2)


a + b: [5 7 9]
a - b: [-3 -3 -3]
a * b: [ 4 10 18]
a / b: [0.25 0.4  0.5 ]
a ** 2: [1 4 9]


In [33]:

# Broadcasting
c = np.array([[1,2,3],[4,5,6]])
d = np.array([1,1,1])
print("Broadcasting sum:\n", c + d)


Broadcasting sum:
 [[2 3 4]
 [5 6 7]]


In [34]:

# -------------------------
# 5. Universal Functions (ufuncs)
# -------------------------
arr = np.array([1,4,9,16])
print("sqrt:", np.sqrt(arr))
print("exp:", np.exp(arr))
print("log:", np.log(arr))
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))


sqrt: [1. 2. 3. 4.]
exp: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
log: [0.         1.38629436 2.19722458 2.77258872]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
cos: [ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [35]:

# -------------------------
# 6. Aggregation Functions
# -------------------------
arr = np.array([[1,2,3],[4,5,6]])
print("Sum:", np.sum(arr))
print("Sum axis 0:", np.sum(arr, axis=0))
print("Sum axis 1:", np.sum(arr, axis=1))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Argmax:", np.argmax(arr))
print("Argmin:", np.argmin(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))


Sum: 21
Sum axis 0: [5 7 9]
Sum axis 1: [ 6 15]
Mean: 3.5
Max: 6
Min: 1
Argmax: 5
Argmin: 0
Standard deviation: 1.707825127659933
Variance: 2.9166666666666665


In [36]:

# -------------------------
# 7. Reshaping and Flattening
# -------------------------
arr = np.arange(12)
print("Original array:", arr)


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [37]:
arr_reshaped = arr.reshape(3,4)
print("Reshaped 3x4 array:\n", arr_reshaped)


Reshaped 3x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
arr_flat = arr_reshaped.flatten()
print("Flattened array:", arr_flat)


Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [39]:
arr_transpose = arr_reshaped.T
print("Transpose:\n", arr_transpose)


Transpose:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [40]:

# -------------------------
# 8. Stacking and Splitting
# -------------------------
a = np.array([1,2,3])
b = np.array([4,5,6])
print("Horizontal stack:", np.hstack((a,b)))


Horizontal stack: [1 2 3 4 5 6]


In [41]:
print("Vertical stack:\n", np.vstack((a,b)))

arr = np.arange(9)
print("Original array:", arr)
print("Split into 3 parts:", np.split(arr, 3))


Vertical stack:
 [[1 2 3]
 [4 5 6]]
Original array: [0 1 2 3 4 5 6 7 8]
Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [42]:

# -------------------------
# 9. Copy vs View
# -------------------------
arr = np.array([1,2,3,4])
arr_view = arr.view()
arr_copy = arr.copy()


In [43]:
arr_view[0] = 100
arr_copy[1] = 200
print("Original after view change:", arr)
print("Original after copy change:", arr)


Original after view change: [100   2   3   4]
Original after copy change: [100   2   3   4]


In [44]:

# -------------------------
# 10. Boolean Indexing & Fancy Indexing
# -------------------------
arr = np.array([10,20,30,40,50])
print("Elements > 25:", arr[arr>25])
indices = [0,2,4]
print("Fancy indexing:", arr[indices])


Elements > 25: [30 40 50]
Fancy indexing: [10 30 50]


In [45]:

# -------------------------
# 11. Random Numbers
# -------------------------
rand_arr = np.random.rand(3,3) # uniform [0,1)
print("Random array:\n", rand_arr)


Random array:
 [[0.04201715 0.97941405 0.07544508]
 [0.78882378 0.04981958 0.80892015]
 [0.01269026 0.61630192 0.09088158]]


In [46]:

rand_int = np.random.randint(0,10,5)
print("Random integers:", rand_int)


Random integers: [4 9 9 9 2]


In [47]:

normal_arr = np.random.randn(3,3) # standard normal
print("Normal distribution array:\n", normal_arr)


Normal distribution array:
 [[-6.94402900e-01 -1.24310366e+00  4.98691897e-02]
 [-5.19016953e-01 -1.18541689e+00 -1.28787925e+00]
 [ 1.79541809e-03  1.09417078e+00  2.02416223e+00]]


In [48]:

# -------------------------
# 12. Linear Algebra Functions
# -------------------------
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix multiplication:\n", np.dot(A,B))


Matrix multiplication:
 [[19 22]
 [43 50]]


In [49]:
print("Matrix determinant:", np.linalg.det(A))


Matrix determinant: -2.0000000000000004


In [50]:
print("Matrix inverse:\n", np.linalg.inv(A))


Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [51]:
print("Eigenvalues and Eigenvectors:\n", np.linalg.eig(A))


Eigenvalues and Eigenvectors:
 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [52]:

# -------------------------
# 13. Saving and Loading Arrays
# -------------------------
np.save('array.npy', arr)
loaded_arr = np.load('array.npy')
print("Loaded array:", loaded_arr)

print("\nAll major NumPy functions executed successfully!")



Loaded array: [10 20 30 40 50]

All major NumPy functions executed successfully!
